# Generated by Django 4.2.16 on 2024-09-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_commander', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('min_quantity', models.IntegerField(blank=True, default=0)),
                ('current_quantity', models.IntegerField(blank=True, default=0)),
                ('priority', models.IntegerField(blank=True, choices=[(0, 'Select Priority'), (1, 'Needed'), (2, 'Will need soon'), (3, 'Would be nice to have'), (4, 'It can wait')], default=0)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('item_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='project_commander.category')),
            ],
        ),
    ]
