# Generated by Django 4.2.16 on 2024-09-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_commander', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('list_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='list_category', to='project_commander.category')),
            ],
        ),
    ]
